version: '3.8'

services:
  db:
    image: mysql:8.0  # 사용할 MySQL 이미지 버전 (예: 8.0, latest)
    restart: always  # 컨테이너가 종료되면 항상 다시 시작
    environment:
      - MYSQL_ROOT_PASSWORD=tiger
      - MYSQL_DATABASE=todo_sch  # 생성할 데이터베이스 이름 (선택 사항)
      - MYSQL_USER=todo_dba  # 생성할 사용자 이름 (선택 사항)
      - MYSQL_PASSWORD=tiger123  # 생성할 사용자 비밀번호 (선택 사항)
    ports:
      - "3306:3306"  # 호스트의 3306 포트를 컨테이너의 3306 포트에 연결
    volumes:
      - ./mysql-data:/var/lib/mysql