spring:
  application:
    name: todo-server
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/todo_sch
    username: todo_dba
    password: tiger123
    driver-class-name: com.mysql.cj.jdbc.Driver